package source;

import componentes.UJPanelImagem;
import java.awt.Color;
import java.awt.Cursor;
import java.text.DecimalFormat;
import javax.swing.SwingConstants;
import util.MPSoCConfig;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Marcelo
 */
public class ChipsetPeripheral_OLD extends javax.swing.JPanel {

    private int router_address;
    private MPSoCConfig mPSoCConfig;
    private MainFrame mainFrame;
    private int type;
    private boolean needReset;

    public ChipsetPeripheral_OLD(MainFrame mainFrame, int router_address, MPSoCConfig mPSoCConfig, int type) {
        this.mainFrame = mainFrame;
        this.router_address = router_address;
        this.mPSoCConfig = mPSoCConfig;
        this.type = type;
        this.needReset = true;
        initComponents();
        
        
                
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DRAMCtrlPanel = new javax.swing.JPanel();
        DRAMLabel = new javax.swing.JLabel();
        bootPanel = new javax.swing.JPanel();
        bootLabel = new javax.swing.JLabel();
        debugPanel = new javax.swing.JPanel();
        debugLabel = new javax.swing.JLabel();
        CLINTPanel = new javax.swing.JPanel();
        CLINTLabel = new javax.swing.JLabel();
        PLICPanel = new javax.swing.JPanel();
        PLICLabel = new javax.swing.JLabel();
        UARTPanel = new javax.swing.JPanel();
        UARTLabel = new javax.swing.JLabel();
        ethernetPanel = new javax.swing.JPanel();
        ethernetLabel = new javax.swing.JLabel();
        SDPanel = new javax.swing.JPanel();
        SDLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.ScrollPane.Border.color"));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(170, 170));
        setMinimumSize(new java.awt.Dimension(170, 170));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(170, 170));
        setLayout(null);

        DRAMCtrlPanel.setBackground(java.awt.Color.orange);
        DRAMCtrlPanel.setLayout(null);

        DRAMLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        DRAMLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DRAMLabel.setText("DRAM");
        DRAMCtrlPanel.add(DRAMLabel);
        DRAMLabel.setBounds(0, -2, 50, 30);

        add(DRAMCtrlPanel);
        DRAMCtrlPanel.setBounds(30, 10, 50, 30);

        bootPanel.setBackground(java.awt.Color.orange);
        bootPanel.setLayout(null);

        bootLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bootLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bootLabel.setText("Boot");
        bootPanel.add(bootLabel);
        bootLabel.setBounds(0, 0, 50, 30);

        add(bootPanel);
        bootPanel.setBounds(100, 10, 50, 30);

        debugPanel.setBackground(java.awt.Color.orange);
        debugPanel.setLayout(null);

        debugLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        debugLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        debugLabel.setText("Debug");
        debugPanel.add(debugLabel);
        debugLabel.setBounds(0, 0, 50, 30);

        add(debugPanel);
        debugPanel.setBounds(30, 50, 50, 30);

        CLINTPanel.setBackground(java.awt.Color.orange);
        CLINTPanel.setLayout(null);

        CLINTLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        CLINTLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLINTLabel.setText("CLINT");
        CLINTPanel.add(CLINTLabel);
        CLINTLabel.setBounds(0, 0, 50, 30);

        add(CLINTPanel);
        CLINTPanel.setBounds(100, 50, 50, 30);

        PLICPanel.setBackground(java.awt.Color.orange);
        PLICPanel.setLayout(null);

        PLICLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        PLICLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PLICLabel.setText("PLIC");
        PLICPanel.add(PLICLabel);
        PLICLabel.setBounds(0, 0, 50, 30);

        add(PLICPanel);
        PLICPanel.setBounds(30, 90, 50, 30);

        UARTPanel.setBackground(java.awt.Color.orange);
        UARTPanel.setLayout(null);

        UARTLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        UARTLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UARTLabel.setText("UART");
        UARTPanel.add(UARTLabel);
        UARTLabel.setBounds(0, 0, 50, 30);

        add(UARTPanel);
        UARTPanel.setBounds(100, 90, 50, 30);

        ethernetPanel.setBackground(java.awt.Color.orange);
        ethernetPanel.setLayout(null);

        ethernetLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ethernetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ethernetLabel.setText("Ethnet");
        ethernetPanel.add(ethernetLabel);
        ethernetLabel.setBounds(0, 0, 50, 30);

        add(ethernetPanel);
        ethernetPanel.setBounds(30, 130, 50, 30);

        SDPanel.setBackground(java.awt.Color.orange);
        SDPanel.setLayout(null);

        SDLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        SDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SDLabel.setText("SD");
        SDPanel.add(SDLabel);
        SDLabel.setBounds(0, 0, 50, 30);

        add(SDPanel);
        SDPanel.setBounds(100, 130, 50, 30);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Chipset");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 70, 17);
    }// </editor-fold>//GEN-END:initComponents

        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLINTLabel;
    private javax.swing.JPanel CLINTPanel;
    private javax.swing.JPanel DRAMCtrlPanel;
    private javax.swing.JLabel DRAMLabel;
    private javax.swing.JLabel PLICLabel;
    private javax.swing.JPanel PLICPanel;
    private javax.swing.JLabel SDLabel;
    private javax.swing.JPanel SDPanel;
    private javax.swing.JLabel UARTLabel;
    private javax.swing.JPanel UARTPanel;
    private javax.swing.JLabel bootLabel;
    private javax.swing.JPanel bootPanel;
    private javax.swing.JLabel debugLabel;
    private javax.swing.JPanel debugPanel;
    private javax.swing.JLabel ethernetLabel;
    private javax.swing.JPanel ethernetPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public int getRouter_address() {
        return router_address;
    }

    public boolean isNeedReset() {
        return needReset;
    }
}
